// Package randomsource provides an in-memory, automatically rotating key source.
package randomsource

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"fmt"
	"strings"
	"sync"
	"time"

	"github.com/veles-security/vcrypt/key"
	"github.com/veles-security/vcrypt/keybuilder"
	"github.com/veles-security/vcrypt/keysource"
	"github.com/veles-security/vcrypt/material"
)

// KeyType identifies the kind and size of key generated by a Source.
type KeyType string

const (
	RSA2048   KeyType = "RSA-2048"
	RSA3072   KeyType = "RSA-3072"
	RSA4096   KeyType = "RSA-4096"
	ECDSAP256 KeyType = "ECDSA-P256"
	ECDSAP384 KeyType = "ECDSA-P384"
	ECDSAP521 KeyType = "ECDSA-P521"
	HMAC256   KeyType = "HMAC-256"
	HMAC384   KeyType = "HMAC-384"
	HMAC512   KeyType = "HMAC-512"
)

// Source generates and rotates ephemeral keys in memory. It retains the key
// from the preceding epoch and pre-generates the key for the following epoch.
type Source struct {
	id       string
	keyType  KeyType
	lifetime time.Duration

	mu       sync.Mutex
	callback func([]key.Key) error
	started  bool
	base     time.Time
	epoch    int64
	keys     map[int64]key.Key
	wake     chan struct{}
	now      func() time.Time
}

// New creates an automatically rotating random source. The lifetime is the
// duration of one key epoch.
func New(id string, keyType KeyType, lifetime time.Duration) (*Source, error) {
	if strings.TrimSpace(id) == "" {
		return nil, fmt.Errorf("random source ID is empty")
	}
	if lifetime <= 0 {
		return nil, fmt.Errorf("random source lifetime must be positive")
	}
	if !validKeyType(keyType) {
		return nil, fmt.Errorf("random source key type %q is unsupported", keyType)
	}
	return &Source{id: id, keyType: keyType, lifetime: lifetime, keys: make(map[int64]key.Key), wake: make(chan struct{}, 1), now: time.Now}, nil
}

func (s *Source) ID() string { return s.id }

// Load returns the previous, current, and future keys. On the first call it
// creates all three, including a previous passive key whose validity began one
// lifetime ago.
func (s *Source) Load() ([]key.Key, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	keys, err := s.rotateLocked(s.now())
	if err == nil {
		s.startLocked()
	}
	return keys, err
}

// SetRefreshCallback supplies the function used to replace this source's keys
// after an automatic rotation.
func (s *Source) SetRefreshCallback(callback func([]key.Key) error) {
	s.mu.Lock()
	s.callback = callback
	s.startLocked()
	s.mu.Unlock()
	select {
	case s.wake <- struct{}{}:
	default:
	}
}

func (s *Source) startLocked() {
	if s.started || s.callback == nil || s.base.IsZero() {
		return
	}
	s.started = true
	go s.watch()
}

func (s *Source) watch() {
	for {
		s.mu.Lock()
		next := s.base.Add(time.Duration(s.epoch+1) * s.lifetime)
		s.mu.Unlock()
		timer := time.NewTimer(time.Until(next))
		select {
		case <-timer.C:
		case <-s.wake:
			if !timer.Stop() {
				select {
				case <-timer.C:
				default:
				}
			}
			continue
		}
		s.mu.Lock()
		keys, err := s.rotateLocked(s.now())
		callback := s.callback
		s.mu.Unlock()
		if err == nil && callback != nil {
			_ = callback(keys) // retain the in-memory state and retry next epoch on store errors
		}
	}
}

func (s *Source) rotateLocked(now time.Time) ([]key.Key, error) {
	if s.base.IsZero() {
		s.base = now
		s.epoch = 0
	} else {
		s.epoch = int64(now.Sub(s.base) / s.lifetime)
	}
	for _, epoch := range []int64{s.epoch - 1, s.epoch, s.epoch + 1} {
		if _, ok := s.keys[epoch]; !ok {
			generated, err := s.generate(epoch)
			if err != nil {
				return nil, err
			}
			s.keys[epoch] = generated
		}
	}
	for epoch := range s.keys {
		if epoch < s.epoch-1 || epoch > s.epoch+1 {
			delete(s.keys, epoch)
		}
	}
	return []key.Key{s.withStatus(s.keys[s.epoch-1], key.KeyStatusPassive), s.withStatus(s.keys[s.epoch], key.KeyStatusActive), s.withStatus(s.keys[s.epoch+1], key.KeyStatusPassive)}, nil
}

func (s *Source) generate(epoch int64) (key.Key, error) {
	var m material.Material
	var err error
	switch s.keyType {
	case RSA2048, RSA3072, RSA4096:
		bits := map[KeyType]int{RSA2048: 2048, RSA3072: 3072, RSA4096: 4096}[s.keyType]
		var generated *rsa.PrivateKey
		generated, err = rsa.GenerateKey(rand.Reader, bits)
		m = &material.PrivateMaterial{Key: generated}
	case ECDSAP256, ECDSAP384, ECDSAP521:
		curve := map[KeyType]elliptic.Curve{ECDSAP256: elliptic.P256(), ECDSAP384: elliptic.P384(), ECDSAP521: elliptic.P521()}[s.keyType]
		var generated *ecdsa.PrivateKey
		generated, err = ecdsa.GenerateKey(curve, rand.Reader)
		m = &material.PrivateMaterial{Key: generated}
	case HMAC256, HMAC384, HMAC512:
		size := map[KeyType]int{HMAC256: 32, HMAC384: 48, HMAC512: 64}[s.keyType]
		secret := make([]byte, size)
		_, err = rand.Read(secret)
		m = &material.SymmetricMaterial{Key: secret}
	}
	if err != nil {
		return key.Key{}, fmt.Errorf("generate %s key: %w", s.keyType, err)
	}
	start := s.base.Add(time.Duration(epoch) * s.lifetime)
	// A key is active for one lifetime and remains valid for one more lifetime
	// while passive, allowing signatures from its active epoch to be verified.
	built, err := keybuilder.Build(key.KeyCandidate{ID: fmt.Sprintf("%s-%d", s.id, epoch), Source: s.id, Status: key.KeyStatusPassive, NotBefore: start, NotAfter: start.Add(2 * s.lifetime), Material: m})
	if err != nil {
		return key.Key{}, fmt.Errorf("build random key: %w", err)
	}
	return *built, nil
}

func (s *Source) withStatus(k key.Key, status key.KeyStatus) key.Key {
	return key.New(key.KeyCandidate{ID: k.ID(), Owner: k.Owner(), Source: k.Source(), Restrictions: k.Restrictions(), Status: status, Priority: k.Priority(), NotBefore: k.NotBefore(), NotAfter: k.NotAfter(), Material: k.Material()}, k.Backend())
}

func validKeyType(t KeyType) bool {
	switch t {
	case RSA2048, RSA3072, RSA4096, ECDSAP256, ECDSAP384, ECDSAP521, HMAC256, HMAC384, HMAC512:
		return true
	}
	return false
}

var _ keysource.SelfRefreshingSource = (*Source)(nil)
