@startuml "concept"

package vapi {
    interface Reader {
        + ReadArtifact[A,C,O](ctx context.Context, carrier C, options ...O) (A, error)
    }
    interface Decoder {
        + Decode[A,O](ctx context.Context, encoded []byte, options ...O) (A, error)
    }
}

package crypto {
    class Service {
        + Sign(ctx, []byte, options...) ([]byte, error)
        + Verify(ctx, []byte, []byte, options...) error
        + Encrypt(ctx, []byte, options...) ([]byte, error)
        + Decrypt(ctx, []byte, options...) ([]byte, error)
    }
}

package keystore {
    class Store {
        + Load(ctx) error
        + Reload(ctx) error
        + Sources() []Source
        + Repository() Repository
    }

    interface Repository {
        + Find(query KeyQuery) []Key
        + Replace(keys []Key, query KeyQuery) []Key
    }

    class KeyQuery {
        + ID KeyID
        + Use Use
        + Operation Operation
        + Algorithm Algorithm
    }
}

package source {
    interface Source {
        + Load(ctx) []Key
        + Reload(ctx) []Key
    }

    class FileSource {
        + Load(ctx) []Key
        + Reload(ctx) []Key
    }

    class JwksSource {
        + Load(ctx) []Key
        + Reload(ctx) []Key
    }

    class HsmSource {
        + Load(ctx) []Key
        + Reload(ctx) []Key
    }

    Source <|.. FileSource
    Source <|.. JwksSource
    Source <|.. HsmSource
}


package key {
    class Key {
        + Status
        + Priority
        + NotBefore
        + NotAfter
        + ID() KeyID
        + Owner() string
        + Source() string
        + Restrictions []Capability
        + Backend() Backend
    }
    class Capability {
        + Use KeyUse
        + Operation KeyOp
        + Algorithm KeyAlg
    }
    interface Backend {
        + Supports(use, operation, algorithm) bool
        + Capabilities() []Capability

        + Sign(ctx, []byte, options...) ([]byte, error)
        + Verify(ctx, []byte, []byte, options...) error
        + Encrypt(ctx, []byte, options...) ([]byte, error)
        + Decrypt(ctx, []byte, options...) ([]byte, error)
    }
    Key *-- Backend
    Key --> Capability
}

package builder {
    class KeyBuilder {
        + Build(candidate KeyCandidate) Key
    }
    class KeyCandidate {
        material Material
        metadata
    }
}

package reader {
    class JwksReader {
        + ReadArtifact(ctx, carrier http.Response, options ...O) ([]KeyCandidate, error)
    }
    class FileReader {
        + ReadArtifact(ctx, carrier Path, options ...O) ([]KeyCandidate, error)
    }
    Reader <|.. JwksReader
    Reader <|.. FileReader
}

package material {
    interface Material {
        Kind()
    }
    class PublicMaterial {
        key PublicKey
    }
    class PrivateMaterial {
        key PrivateKey
    }
    class SymetricMaterial {
        key PrivateKey
    }
    Material <|.. PublicMaterial
    Material <|.. PrivateMaterial
    Material <|.. SymetricMaterial
}

package decoder {
    class DecoderRegistry {
        - decoders []Decoder[KeyCandidate,O]
        + Register(decoder Decoder[KeyCandidate,O])
        + Decode(keyType, encoded []byte) (KeyCandidate, error)
    }
}

package backend {
    class Registry {
        - backends []BackendFactory
        + Register(backend BackendFactory)
        + BackendFor(material Material) Backend
    }

    interface BackendFactory {
        + Supports(m Material) bool
        + New(material Material) Backend
    }
}

package scheme.ec {
    class EcBackendFactory {
        + Supports(m Material) bool
        + New(material Material) EcBackend
    }

    class EcBackend {
        - material Material

        + Supports(use, operation, algorithm) bool
        + Capabilities() []Capability
        + Verify(ctx, []byte, []byte, options...) error
        + Encrypt(ctx, []byte, options...) ([]byte, error)
        + Decrypt(ctx, []byte, options...) ([]byte, error)
    }
}

package scheme.rsa {
    class RsaBackendFactory {
        + Supports(m Material) bool
        + New(material Material) RsaBackend
    }

    class RsaBackend {
        - material Material

        + Supports(use, operation, algorithm) bool
        + Capabilities() []Capability
        + Verify(ctx, []byte, []byte, options...) error
        + Encrypt(ctx, []byte, options...) ([]byte, error)
        + Decrypt(ctx, []byte, options...) ([]byte, error)
    }

    class RsaDecoder {
        Decode(ctx, encoded []byte, options ...O) (KeyCandidate, error)
    }
    Decoder <|.. RsaDecoder
    RsaDecoder --> DecoderRegistry : Register()
}

package scheme.hsm {
    class HsmBackendFactory {
        + Supports(m Material) bool
        + New(material Material) HsmBackend
    }

    class HsmBackend {
        - material Material

        + Supports(use, operation, algorithm) bool
        + Capabilities() []Capability
        + Verify(ctx, []byte, []byte, options...) error
        + Encrypt(ctx, []byte, options...) ([]byte, error)
        + Decrypt(ctx, []byte, options...) ([]byte, error)
    }
}

Service o-- Store

Store o-- Repository
Store o-- Source


Repository o-- Key

KeyBuilder --> Key
KeyBuilder --> Registry

Backend <|.. RsaBackend
Backend <|.. EcBackend
Backend <|.. HsmBackend


Registry o-- BackendFactory

BackendFactory <|.. RsaBackendFactory
BackendFactory <|.. EcBackendFactory
BackendFactory <|.. HsmBackendFactory

Source --> KeyBuilder

KeyCandidate *-- Material

JwksReader --> DecoderRegistry
JwksSource --> JwksReader

@enduml